# Generated by Django 5.1.2 on 2024-11-16 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='previous_experience',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
