# Generated by Django 5.1.1 on 2024-10-19 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0002_alter_medico_licensenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medico',
            old_name='licenseNumber',
            new_name='license_number',
        ),
        migrations.RenameField(
            model_name='medico',
            old_name='previousExperience',
            new_name='previous_experience',
        ),
    ]
