# Generated by Django 5.1.1 on 2024-10-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('modificatedDate', models.DateTimeField(auto_now_add=True)),
                ('deleteDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
