# Generated by Django 5.1.1 on 2024-10-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planEjercicio', '0003_remove_planejercicio_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='planejercicio',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
