# Generated by Django 5.1.1 on 2024-10-19 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planEjercicio', '0004_planejercicio_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planejercicio',
            old_name='createdDate',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='planejercicio',
            old_name='deleteDate',
            new_name='delete',
        ),
        migrations.RenameField(
            model_name='planejercicio',
            old_name='modificatedDate',
            new_name='modificated',
        ),
    ]
