# Generated by Django 5.1.1 on 2024-10-19 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='createDate',
            new_name='create',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='deleteDate',
            new_name='delete',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='modificatedDate',
            new_name='modificated',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='lastname',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
