# Generated by Django 5.1.1 on 2024-11-08 20:33

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medico', '0001_initial'),
        ('planAlimentacion', '0001_initial'),
        ('planEjercicio', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vegetarian', models.BooleanField()),
                ('hypertension', models.BooleanField()),
                ('diabetic', models.BooleanField()),
                ('others', models.CharField(blank=True, max_length=500)),
                ('assigned_medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medico.medico')),
                ('plan_alimentacion', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='planAlimentacion.planalimentacion')),
                ('plan_ejercicio', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='planEjercicio.planejercicio')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('usuario.usuario',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
