# Generated by Django 5.1.1 on 2024-10-15 21:40

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planAlimentacion', '0001_initial'),
        ('planEjercicio', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuario.usuario')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=3)),
                ('height', models.DecimalField(decimal_places=2, max_digits=3)),
                ('vegetarian', models.BooleanField()),
                ('hypertension', models.BooleanField()),
                ('diabetic', models.BooleanField()),
                ('others', models.CharField(max_length=500)),
                ('planAlimentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planAlimentacion.planalimentacion')),
                ('planEjercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planEjercicio.planejercicio')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('usuario.usuario',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
