# Generated by Django 5.1.1 on 2024-10-18 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_cliente_height_alter_cliente_others_and_more'),
        ('medico', '0002_alter_medico_licensenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='assigned_medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medico.medico'),
        ),
    ]
