# Generated by Django 5.1.2 on 2024-11-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_cliente_plan_alimentacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='diabetic',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='hypertension',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='others',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='vegetarian',
            field=models.BooleanField(null=True),
        ),
    ]
