# Generated by Django 5.1.2 on 2024-11-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_alter_cliente_diabetic_alter_cliente_hypertension_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='genre',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=10, null=True),
        ),
    ]
