# Generated by Django 5.1.1 on 2024-11-17 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_cliente_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='vegan',
            field=models.BooleanField(null=True),
        ),
    ]
