# Generated by Django 5.1.2 on 2024-11-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_cliente_vegan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='vegan',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='diabetic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='hypertension',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='vegetarian',
            field=models.BooleanField(default=False),
        ),
    ]
