# Generated by Django 5.1.2 on 2024-11-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_remove_cliente_vegan_alter_cliente_diabetic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='sugerencias',
            field=models.TextField(blank=True, null=True),
        ),
    ]
