# Generated by Django 5.1.1 on 2024-11-19 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_cliente_sugerencias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='plan_alimentacion',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Vegetariana'), (2, 'Vegana'), (3, 'Proteica')]),
        ),
    ]
