# Generated by Django 5.1.1 on 2024-11-19 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0008_alter_cliente_plan_alimentacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='plan_ejercicio',
        ),
    ]
