# Generated by Django 5.1.1 on 2024-11-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0009_remove_cliente_plan_ejercicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='plan_alimentacion',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Vegetariana'), (2, 'Vegana'), (3, 'Proteica')], null=True),
        ),
    ]
