# Generated by Django 5.1.1 on 2024-11-19 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planAlimentacion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlanAlimentacion',
        ),
    ]
