# Generated by Django 5.1.1 on 2024-10-15 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('planAlimentacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planalimentacion',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente'),
        ),
    ]
