# Generated by Django 5.1.1 on 2024-11-08 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('conversacion', '0001_initial'),
        ('medico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacion',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to='cliente.cliente'),
        ),
        migrations.AddField(
            model_name='conversacion',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversacion',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to='medico.medico'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversacion.conversacion'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
