# Generated by Django 5.1.1 on 2024-10-15 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('conversacion', '0001_initial'),
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacion',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente'),
        ),
        migrations.AddField(
            model_name='conversacion',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medico.medico'),
        ),
        migrations.AddField(
            model_name='conversacion',
            name='sender_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
