# Generated by Django 5.1.1 on 2024-11-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversacion', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='delete',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='modificated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
