# Generated by Django 5.1.1 on 2024-10-19 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_rename_planalimentacion_cliente_plan_alimentacion_and_more'),
        ('conversacion', '0002_initial'),
        ('medico', '0003_rename_licensenumber_medico_license_number_and_more'),
        ('usuario', '0002_rename_createdate_usuario_create_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversacion',
            old_name='createdDate',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='conversacion',
            name='deleteDate',
        ),
        migrations.RemoveField(
            model_name='conversacion',
            name='message',
        ),
        migrations.RemoveField(
            model_name='conversacion',
            name='modificatedDate',
        ),
        migrations.RemoveField(
            model_name='conversacion',
            name='sender_content_type',
        ),
        migrations.RemoveField(
            model_name='conversacion',
            name='sender_object_id',
        ),
        migrations.AddField(
            model_name='conversacion',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_created_by', to='usuario.usuario'),
        ),
        migrations.AddField(
            model_name='conversacion',
            name='delete',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='conversacion',
            name='modificated',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='conversacion',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to='cliente.cliente'),
        ),
        migrations.AlterField(
            model_name='conversacion',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to='medico.medico'),
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modificated', models.DateTimeField(default=None)),
                ('delete', models.DateTimeField(default=None)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversacion.conversacion')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
    ]
